# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_page_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_video_page(object):
    def setupUi(self, image_page):
        image_page.setObjectName("image_page")
        image_page.resize(958, 665)
        image_page.setStyleSheet("background-color:#2C3E50;")
        self.label = QtWidgets.QLabel(image_page)
        self.label.setGeometry(QtCore.QRect(60, 60, 181, 51))
        self.label.setStyleSheet("color:white;\n"
"font: 14pt \"Times New Roman\";\n"
"border: 2px solid black;\n"
"border-radius: 8px;\n"
"padding: 2px;\n"
"")
        self.label.setObjectName("label")
        self.search_edit = QtWidgets.QLineEdit(image_page)
        self.search_edit.setGeometry(QtCore.QRect(60, 130, 361, 31))
        self.search_edit.setStyleSheet("background-color:white;\n"
"border-radius: 5px;")
        self.search_edit.setObjectName("search_edit")
        self.browse_button = QtWidgets.QPushButton(image_page)
        self.browse_button.setGeometry(QtCore.QRect(440, 120, 101, 51))
        self.browse_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.browse_button.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color:#3498DB;\n"
"border:2px solid;\n"
"border-color:black;\n"
"border-radius: 5px;")
        self.browse_button.setObjectName("browse_button")
        self.input_video = QtWidgets.QLabel(image_page)
        self.input_video.setGeometry(QtCore.QRect(60, 250, 411, 271))
        self.input_video.setScaledContents(True)
        self.input_video.setStyleSheet("border:2px solid black;\n"
"border-radius: 3px;\n"
"")
        self.input_video.setText("")
        self.input_video.setObjectName("input_video")
        self.output_video = QtWidgets.QLabel(image_page)
        self.output_video.setScaledContents(True)
        self.output_video.setGeometry(QtCore.QRect(500, 250, 411, 271))

        self.output_video.setStyleSheet("border:2px solid black;\n"
"border-radius: 3px;\n"
"")
        self.output_video.setText("")
        self.output_video.setObjectName("output_video")
        self.label_2 = QtWidgets.QLabel(image_page)
        self.label_2.setGeometry(QtCore.QRect(210, 530, 111, 41))
        self.label_2.setStyleSheet("color:white;\n"
"font:10pt;\n"
"border: 2px solid black;\n"
"border-radius: 5px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.output_image_2 = QtWidgets.QLabel(image_page)
        self.output_image_2.setGeometry(QtCore.QRect(660, 530, 131, 41))
        self.output_image_2.setStyleSheet("color:white;\n"
"font:10pt;\n"
"border: 2px solid black;\n"
"border-radius: 5px;")
        self.output_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_image_2.setObjectName("output_image_2")
        self.home_button_video = QtWidgets.QPushButton(image_page)
        self.home_button_video.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.home_button_video.setGeometry(QtCore.QRect(300, 600, 91, 41))
        self.home_button_video.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color:#3498DB;\n"
"border:2px solid;\n"
"border-color:black;\n"
"border-radius: 5px;")
        self.home_button_video.setObjectName("home_button_video")
        self.clear_button_video = QtWidgets.QPushButton(image_page)
        self.clear_button_video.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_button_video.setGeometry(QtCore.QRect(570, 600, 91, 41))
        self.clear_button_video.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color:#3498DB;\n"
"border:2px solid;\n"
"border-color:black;\n"
"border-radius: 5px;")
        self.clear_button_video.setObjectName("clear_button_video")
        self.detect_button = QtWidgets.QPushButton(image_page)
        self.detect_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detect_button.setGeometry(QtCore.QRect(390, 530, 181, 41))
        self.detect_button.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color:#3498DB;\n"
"border:2px solid;\n"
"border-color:black;\n"
"border-radius: 5px;")
        self.detect_button.setObjectName("detect_button")

        self.retranslateUi(image_page)
        QtCore.QMetaObject.connectSlotsByName(image_page)

    def retranslateUi(self, image_page):
        _translate = QtCore.QCoreApplication.translate
        image_page.setWindowTitle(_translate("image_page", "Lane Detection on Image"))
        self.label.setText(_translate("image_page", "Select a video:"))
        self.search_edit.setText(_translate("image_page", "Browse a video"))
        self.browse_button.setText(_translate("image_page", "Browse"))
        self.label_2.setText(_translate("image_page", "Input Video"))
        self.output_image_2.setText(_translate("image_page", "Output Video"))
        self.home_button_video.setText(_translate("image_page", "Home"))
        self.clear_button_video.setText(_translate("image_page", "Clear"))
        self.detect_button.setText(_translate("image_page", "Detect Road Lanes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    image_page = QtWidgets.QWidget()
    ui = Ui_video_page()
    ui.setupUi(image_page)
    image_page.show()
    sys.exit(app.exec_())
